stages:
- name: Build Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: reti/mydb
      registry: 127.0.0.1:34891
timeout: 60
notification: {}
